Blog App: Add API Endpoints
DammyShittu/Blog-App pull request #10
Opened 2021-12-16 16:48 UTC by DammyShittu

# In this PR, we completed the following requirements,

- Create an API endpoint to list all posts.

- Create an API endpoint to list all comments for a post.

- Create an API endpoint to add a comment to a post. Remember that the owner of the comment is the user that makes it; it should not be set by passing a parameter.

- Add authentication to your API endpoints.

- Your API endpoints should receive JSON and respond JSON as well.

2021-12-16 18:20 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @DammyShittu  and @medaminedev66, 

Good job so far!

There are some issues that you still need to work on to go further but you are almost there!


 ## Required Changes ♻️
_Please check the inline comments for my suggestions_ :arrow_down:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] It will be better if you try to document your API endpoints.  

Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-16 18:20 UTC, sinansevgi commented on config/routes.rb
> +
- [ ] You should have API endpoints for authentication. Currently, I can't log in or sign-up to the application. (via HTTP requests)

Note:
I tried to create a user account from the HTML form and test the implemented endpoints.

2021-12-16 18:20 UTC, sinansevgi commented on app/controllers/api/v1/posts_controller.rb
> +  end
- [ ] Users can't access posts#index endpoint because of authorization. I am getting the below HTML response instead of JSON response.

![Screenshot 2021-12-16 at 20-55-36 Action Controller Exception caught](https://user-images.githubusercontent.com/1642014/146423840-a9d93b84-361e-423e-930b-ca6f6b1f993b.png)

2021-12-16 18:20 UTC, sinansevgi commented on app/controllers/api/v1/comments_controller.rb
> +  end
- [ ] I couldn't test the comment#create endpoint since there is no way to log in the application via HTTP requests

2021-12-16 18:20 UTC, sinansevgi commented on app/controllers/api/v1/comments_controller.rb
> +  end
- [ ] I can't access comments of my post. 

![Screenshot 2021-12-16 at 21-06-26 Action Controller Exception caught](https://user-images.githubusercontent.com/1642014/146426275-791fa3a0-281b-4dbc-9bf2-9dee238287e0.png)

2021-12-17 12:59 UTC, DammyShittu commented
Hi reviewer, 

We have successfully implemented the sign-up and login authentications and here are some commands that you can run to test them out.

### SIGN UP 👇 

`$ curl -XPOST -H "Content-Type: application/json" -d '{ "user": { "email": "test@example.com", "password": "12345678" } }' http://localhost:3000/users`

### SIGN IN 👇

`curl -XPOST -i -H "Content-Type: application/json" -d '{ "user": { "email": "test@example.com", "password": "12345678" } }' http://localhost:3000/users/sign_in`

2021-12-17 13:06 UTC, AshakaE approved these changes
### Hi @DammyShittu  & @medaminedev66   🙋‍♀️, 

# STATUS APPROVED ✔
   
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-17 13:18 UTC, DammyShittu commented
Thank you, @AshakaE 👏

2021-12-17 13:18 UTC, merged